name: Build

on:
  push:
    tags:
      - 'v*' # This triggers the workflow when you push a tag starting with 'v'
    branches:
      - master # This keeps the build running on normal pushes to check for errors

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          fetch-tags: true

      - name: Setup JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew build

      - name: Upload to CurseForge
        if: startsWith(github.ref, 'refs/tags/v') # ONLY runs if this is a tag push
        uses: itsmeow/curseforge-upload@v3
        with:
            token: ${{ secrets.CURSEFORGE_TOKEN }} #sorry, has to kept secret for security reasons
            project_id: '1065362' # is project ID
            file_path: 'build/libs/moraymobs-*.jar'
            game_versions: '1.21.1'
            release_type: 'release'
            display_name: 'Moraysmobs'
            changelog: '-Added Dullahan (add more later)'
            changelog_type: 'markdown'
      #  thanks itsmoew!